---
- name: create user wide binary path directory 
  ansible.builtin.file:
    path: "$HOME/.cargo"
    state: directory

- name: install packages
  become: yes
  ansible.builtin.package:
    state: latest
    name:
      - bat
      - cargo
      - git
      - golang
      - htop
      - make
      - openssl
      - rust
      - snapd
      - tree
      - neovim
      - zsh
      - exa

