# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
format = """$character"""

# move the rest of the prompt to the right
right_format = """$all"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # iThe name of the module we are configuring is 'character'
success_symbol = '[](bold blue)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
